const PRODUCTS = [
  { id: 1, sku: 'SN-IP15PM', name: 'iPhone 15 Pro Max 256GB สีไทเทเนียม', category: 'electronics', tags: ['top', 'flash'], emoji: '📱', price: 35900, originalPrice: 45900, rating: 4.9, sold: 15420, stock: 50, shop: 'Apple Official', shopBadge: 'Official', badge: 'sale', desc: 'iPhone 15 Pro Max มาพร้อมชิป A17 Pro กล้อง 48MP Action Button และ Dynamic Island ที่ทรงพลังที่สุด', specs: { หน้าจอ: '6.7 นิ้ว Super Retina XDR', ชิป: 'A17 Pro', กล้อง: '48MP + 12MP + 12MP', แบตเตอรี่: '4422 mAh', ระบบ: 'iOS 17', สี: 'ไทเทเนียม' }, reviews: [{ user: 'สมชาย', rating: 5, comment: 'ดีมากๆ ของใหม่แท้ ส่งไว', date: '2025-01-15' }, { user: 'มาลี', rating: 5, comment: 'สวยมาก คุ้มค่า', date: '2025-01-10' }] },
  { id: 2, sku: 'SN-GS25U', name: 'Samsung Galaxy S25 Ultra 512GB', category: 'electronics', tags: ['top', 'new'], emoji: '📲', price: 42900, originalPrice: 52900, rating: 4.8, sold: 8320, stock: 30, shop: 'Samsung Thailand', shopBadge: 'Official', badge: 'new', desc: 'Galaxy S25 Ultra พร้อม S Pen สมาร์ทโฟน AI ที่ทรงพลัง', specs: { หน้าจอ: '6.9 นิ้ว Dynamic AMOLED', ชิป: 'Snapdragon 8 Elite', กล้อง: '200MP', แบตเตอรี่: '5000 mAh' }, reviews: [{ user: 'วิชัย', rating: 5, comment: 'ดีมาก Samsung ไม่ผิดหวัง', date: '2025-02-01' }] },
  { id: 3, sku: 'SN-APP2', name: 'AirPods Pro 2nd Generation', category: 'electronics', tags: ['top', 'flash'], emoji: '🎧', price: 7490, originalPrice: 9990, rating: 4.8, sold: 22100, stock: 100, shop: 'Apple Official', shopBadge: 'Official', badge: 'sale', desc: 'AirPods Pro รุ่น 2 พร้อม Active Noise Cancellation และ Adaptive Audio', specs: { ประเภท: 'In-Ear TWS', การตัดเสียง: 'ANC', แบตเตอรี่: '30 ชั่วโมง', เชื่อมต่อ: 'Bluetooth 5.3' }, reviews: [] },
  { id: 4, sku: 'SN-MBA-M3', name: 'MacBook Air M3 13" 8GB/256GB', category: 'electronics', tags: ['top'], emoji: '💻', price: 39900, originalPrice: 44900, rating: 4.9, sold: 5600, stock: 20, shop: 'Apple Official', shopBadge: 'Official', badge: 'hot', desc: 'MacBook Air พร้อมชิป M3 บางเบา แบตอึด ทำงานเร็ว', specs: { จอ: '13.6 นิ้ว Liquid Retina', ชิป: 'Apple M3', RAM: '8GB', SSD: '256GB' }, reviews: [] },
  { id: 5, sku: 'SN-POLO-M', name: 'เสื้อโปโลชาย Premium Cotton', category: 'fashion', tags: ['top', 'new'], emoji: '👔', price: 399, originalPrice: 890, rating: 4.7, sold: 45200, stock: 500, shop: 'Fashion House', shopBadge: 'Mall', badge: 'sale', desc: 'เสื้อโปโลชายผ้าคอตตอน 100% ระบายอากาศได้ดี มีให้เลือกหลายสี', specs: { วัสดุ: 'Cotton 100%', ไซส์: 'S, M, L, XL, XXL', ประเภท: 'โปโล' }, reviews: [] },
  { id: 6, sku: 'SN-BAG-L', name: 'กระเป๋าสะพายข้าง Leather ของแท้', category: 'fashion', tags: ['top', 'flash'], emoji: '👜', price: 1290, originalPrice: 2990, rating: 4.6, sold: 8900, stock: 80, shop: 'Bag Lady', shopBadge: 'Mall', badge: 'sale', desc: 'กระเป๋าหนังแท้ ทรงทันสมัย จุของได้เยอะ ทนทาน', specs: { วัสดุ: 'Genuine Leather', ขนาด: '30x20x10 ซม.', สี: 'ดำ, น้ำตาล, ชมพู' }, reviews: [] },
  { id: 7, sku: 'SN-SUN-C', name: 'ครีมกันแดด SPF50+ PA++++', category: 'beauty', tags: ['top', 'flash'], emoji: '🧴', price: 199, originalPrice: 450, rating: 4.8, sold: 67800, stock: 1000, shop: 'Beauty Box', shopBadge: 'Mall', badge: 'sale', desc: 'ครีมกันแดดสูตรน้ำเบา ไม่มัน ไม่หนักหน้า กันน้ำ เหมาะทุกสภาพผิว', specs: { SPF: '50+', PA: 'PA++++', ประเภทผิว: 'ทุกสภาพผิว', ขนาด: '50 ml' }, reviews: [] },
  { id: 8, sku: 'SN-VITC-S', name: 'เซรั่มวิตามินซี 30ml', category: 'beauty', tags: ['top', 'new'], emoji: '✨', price: 349, originalPrice: 890, rating: 4.7, sold: 34500, stock: 300, shop: 'Glow Lab', shopBadge: 'Mall', badge: 'new', desc: 'เซรั่มวิตามินซีเข้มข้น 20% ช่วยให้ผิวกระจ่างใส ลดจุดด่างดำ', specs: { วิตามินซี: '20%', ขนาด: '30 ml', สูตร: 'Oil-free' }, reviews: [] },
  { id: 9, sku: 'SN-SOFA-L', name: 'โซฟา L-Shape 3 ที่นั่ง ผ้ากำมะหยี่', category: 'home', tags: ['top'], emoji: '🛋️', price: 8900, originalPrice: 18900, rating: 4.5, sold: 1200, stock: 15, shop: 'Homecraft', shopBadge: 'Mall', badge: 'sale', desc: 'โซฟา L-Shape สุดหรู ผ้ากำมะหยี่นุ่มนวล รองรับทุกมุมของห้อง', specs: { วัสดุ: 'กำมะหยี่', ขนาด: '280x160 ซม.', สี: 'เทา, เขียว, น้ำเงิน', น้ำหนักรับ: '300 กก.' }, reviews: [] },
  { id: 10, sku: 'SN-NIKE-AM', name: 'รองเท้าวิ่ง Nike Air Max 2025', category: 'sports', tags: ['top', 'new'], emoji: '👟', price: 3290, originalPrice: 5500, rating: 4.9, sold: 12300, stock: 60, shop: 'Nike Official', shopBadge: 'Official', badge: 'new', desc: 'Nike Air Max 2025 เทคโนโลยี Air ใหม่ เบา นุ่ม รองรับแรงกระแทกสูง', specs: { วัสดุ: 'Flyknit', พื้น: 'Air Max', ไซส์: '38-46', น้ำหนัก: '280g' }, reviews: [] },
  { id: 11, sku: 'SN-MAMA-TYK', name: 'มาม่าถ้วย รสต้มยำกุ้ง แพ็ค12', category: 'food', tags: ['top', 'flash'], emoji: '🍜', price: 139, originalPrice: 180, rating: 4.9, sold: 199000, stock: 5000, shop: 'Mama Official', shopBadge: 'Official', badge: 'hot', desc: 'มาม่าถ้วยรสต้มยำกุ้ง รสชาติเข้มข้น อร่อยทุกคำ', specs: { ปริมาณ: '70g x 12 ถ้วย', รส: 'ต้มยำกุ้ง', อายุการเก็บ: '12 เดือน' }, reviews: [] },
  { id: 12, sku: 'SN-BEAR-80', name: 'ตุ๊กตาหมีขนาดใหญ่ 80cm', category: 'toys', tags: ['new'], emoji: '🧸', price: 590, originalPrice: 1200, rating: 4.8, sold: 6700, stock: 200, shop: 'Toy World', shopBadge: '', badge: 'new', desc: 'ตุ๊กตาหมีขนาดใหญ่ ผ้ากำมะหยี่นุ่ม ซักได้ ปลอดภัยสำหรับเด็ก', specs: { ขนาด: '80 ซม.', วัสดุ: 'กำมะหยี่ Polyester', อายุ: '3+ ปี' }, reviews: [] },
  { id: 13, sku: 'SN-BOOK-AH', name: 'หนังสือ "Atomic Habits" ฉบับภาษาไทย', category: 'books', tags: ['top', 'new'], emoji: '📚', price: 290, originalPrice: 450, rating: 4.9, sold: 23000, stock: 300, shop: 'Bookdee', shopBadge: 'Mall', badge: 'hot', desc: 'หนังสือ Atomic Habits ฉบับแปลไทย เปลี่ยนนิสัยเปลี่ยนชีวิต', specs: { หน้า: '360 หน้า', ภาษา: 'ไทย', สำนักพิมพ์: 'Bookdee' }, reviews: [] },
  { id: 14, sku: 'SN-TIRE-MIC', name: 'ยางรถยนต์ Michelin 195/65R15', category: 'auto', tags: ['top'], emoji: '🚗', price: 2490, originalPrice: 3490, rating: 4.7, sold: 4500, stock: 100, shop: 'Michelin', shopBadge: 'Official', badge: 'sale', desc: 'ยางรถยนต์ Michelin รุ่น Energy XM2+ ประหยัดน้ำมัน ปลอดภัย', specs: { ขนาด: '195/65R15', ยี่ห้อ: 'Michelin', รุ่น: 'Energy XM2+' }, reviews: [] },
  { id: 15, sku: 'SN-PET-RC10', name: 'อาหารสุนัข Royal Canin 10kg', category: 'pets', tags: ['top', 'flash'], emoji: '🐾', price: 1290, originalPrice: 1890, rating: 4.9, sold: 15600, stock: 200, shop: 'Pet Store', shopBadge: 'Mall', badge: 'sale', desc: 'อาหารสุนัขโต Royal Canin สูตร Medium Adult ครบคุณค่าสารอาหาร', specs: { น้ำหนัก: '10 กก.', อายุสุนัข: '1-7 ปี', สูตร: 'Medium Adult' }, reviews: [] },
  { id: 16, sku: 'SN-CAM-SA74', name: 'กล้อง Sony A7 IV Full Frame', category: 'electronics', tags: ['new'], emoji: '📷', price: 89900, originalPrice: 99900, rating: 4.9, sold: 890, stock: 10, shop: 'Sony Official', shopBadge: 'Official', badge: 'new', desc: 'กล้อง Mirrorless Full Frame Sony A7 IV ความละเอียด 33MP ถ่ายวิดีโอ 4K', specs: { ความละเอียด: '33 MP', วิดีโอ: '4K 60fps', ISO: '100-51200', แบตเตอรี่: '580 ช็อต' }, reviews: [] },
  { id: 17, sku: 'SN-DRS-FLR', name: 'เดรสสั้น Casual Floral ลายดอกไม้', category: 'fashion', tags: ['new', 'flash'], emoji: '👗', price: 349, originalPrice: 790, rating: 4.6, sold: 18900, stock: 300, shop: 'Style Me', shopBadge: 'Mall', badge: 'sale', desc: 'เดรสสั้นลายดอกไม้ สไตล์ Casual ใส่สบาย เหมาะทุกโอกาส', specs: { วัสดุ: 'Polyester', ไซส์: 'S-XL', ลาย: 'Floral' }, reviews: [] },
  { id: 18, sku: 'SN-LIP-MAC', name: 'ลิปสติก MAC Retro Matte', category: 'beauty', tags: ['top', 'flash'], emoji: '💄', price: 890, originalPrice: 1200, rating: 4.8, sold: 34200, stock: 150, shop: 'MAC Cosmetics', shopBadge: 'Official', badge: 'sale', desc: 'ลิปสติก MAC Retro Matte สีเข้ม ติดทนนาน 12 ชั่วโมง', specs: { สูตร: 'Matte', ติดทน: '12 ชั่วโมง', ขนาด: '3g' }, reviews: [] },
  { id: 19, sku: 'SN-NEG-VRT', name: 'เครื่องชงกาแฟ Nespresso Vertuo', category: 'home', tags: ['top', 'new'], emoji: '☕', price: 6990, originalPrice: 9990, rating: 4.8, sold: 5600, stock: 40, shop: 'Nespresso', shopBadge: 'Official', badge: 'new', desc: 'เครื่องชงกาแฟแคปซูล Nespresso Vertuo Plus ชงง่าย รสชาติเข้มข้น', specs: { ความดัน: '19 บาร์', ถังน้ำ: '1.1 ลิตร', เวลาอุ่น: '20 วิ' }, reviews: [] },
  { id: 20, sku: 'SN-FIT-BND', name: 'ฟิตเนส Resistance Band Set 5ชิ้น', category: 'sports', tags: ['flash', 'new'], emoji: '💪', price: 299, originalPrice: 699, rating: 4.7, sold: 28900, stock: 500, shop: 'FitGear', shopBadge: 'Mall', badge: 'sale', desc: 'ยางยืดออกกำลังกายชุด 5 ชิ้น แรงต้านต่างกัน เก็บสะดวก', specs: { จำนวน: '5 ชิ้น', แรงต้าน: '5-40 ปอนด์', วัสดุ: 'Natural Latex' }, reviews: [] },
];

const VOUCHERS = [
  { code: 'SHOP50', desc: 'ลด ฿50 เมื่อซื้อครบ ฿500', discount: 50, minOrder: 500 },
  { code: 'FREESHIP', desc: 'ส่งฟรีทุกออเดอร์', discount: 40, minOrder: 0 },
  { code: 'NEW200', desc: 'ลด ฿200 สำหรับสมาชิกใหม่', discount: 200, minOrder: 1000 },
];
